on:
  pull_request_target:
    types:
      - closed

jobs:
  milestone_pr:
    name: Milestone PR
    runs-on: ubuntu-latest
    steps:
      - uses: stefanv/attach-next-milestone@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
